version: "3.9"

services:
  api:
    build:
       context: ..
       dockerfile: Docker/Dockerfile
    container_name: nexfinance_api
    ports:
      - "5163:5163"  # HTTP
      - "7075:7075"  # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=nexfinance_db;Username=postgres;Password=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: nexfinance_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nexfinance"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_DB: nexfinance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ../DataBase/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
       